apiVersion: v1
kind: Service
metadata:
  labels:
    app: lostandfound-sensorhub
  name: lostandfound-sensorhub
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: lostandfound-sensorhub
  type: ClusterIP
